version: '3'

services:
  mail:
    container_name: mail_client
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    command: python3 /app/src/main.py
    env_file:
      - email.env


